### ISSUE TITLE
a question about work

### ISSUE THREAD

**Issue by Christian-lyc** [tanglang96/MDENAS#2]
Thank you for your test code, do you have training code or ProxylessNAS training code? I'm a beginner with NAS. Thank you.

**Comment by zhengxiawu** [comment]
The training code for CIFAR10 is in https://github.com/zhengxiawu/pt.darts
The training code for ImageNet please Contact @tanglang96, or the author in ProxylessNAS.

**Comment by Christian-lyc** [comment]
Thank you so much.
